export const REMOVE_FAVORITE_USER = "REMOVE_FAVORITE_USER";
export const GET_FROM_LOCAL_STORAGE = "GET_FROM_LOCAL_STORAGE";
export const SAVE_FAVORITE_USER = "SAVE_FAVORITE_USER";

export const CONSTANT_LOCAL_STORAGE_NAME = "favoritesUsers";
